const first = () => {
  return (
    <div>
      <h1>첫번째 화면입니다.</h1>
      <h1>검색창</h1>
      <h1>상품사진</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
      <h1>First</h1>
    </div>
  );
};
export default first;
